### ISSUE TITLE
Update the settings and schema files 

### ISSUE THREAD

**Issue by adrian-cid** [adrian-cid/node_revision_delete#16]
<h3 id="summary-problem-motivation">Problem/Motivation</h3>

Now that two new configurations were added in #13 and #15 we need to update the settings and schema files.

<h3 id="summary-proposed-resolution">Proposed resolution</h3>

Merge the node_revision_delete_when_to_delete variable into the node_revision_delete_track variable and add the others variables into the node_revision_delete_track variable something like this:

```
node_revision_delete_track:
  article: 
             revisions_to_keep: 5
             when_to_delete: 1
             minimun_age_to_delete: 1
```

<h3 id="summary-remaining-tasks">Remaining tasks</h3>
None.

<h3 id="summary-ui-changes">User interface changes</h3>
None.

<h3 id="summary-api-changes">API changes</h3>
None.

<h3 id="summary-data-model-changes">Data model changes</h3>
The settings and schema files will be changed.
